### PR TITLE
downloads chrome driver using url from google's new json endpoint

### PR DESCRIPTION
**Pull request by shawnCaza**
On the surface the driver download seems to work, proper directory is added to PATH, but selenium isn't recognizing the driver.

Can anyone spot what I'm missing?

### CODE REVIEW

**Comment by GQAssurance** [comment]
Not a simple fix; there's basically 4 things that changed all at once for 115+ chromedriver:

- The URLs to get version lists + binaries
- The formatting of the version lists (now it's JSON)
- the MacOS naming convention
- The zip files now have binaries inside a directory

I have prototyped changes that I hope will be backwards compatible, and should make a pull request shortly.

**Comment by shawnCaza** [comment]
There's [a bug in Chrome 115 for mac](https://github.com/GoogleChromeLabs/chrome-for-testing/issues/30#issuecomment-1643741069) where the chrome binary needs to be specified.

Once I set the location using:
```
options = webdriver.ChromeOptions()
    options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
```

This pull release works as excepted on Mac x64.

**Comment by GQAssurance** [comment]
Your PR would break backwards compatibility, which is fine in the long term (who tests more than a few version backwards anyways?)  but in the short term it means people testing 108-114 will not get a chromedriver

it also changes the installed directory, which others might depend on for other reasons

**Comment by shawnCaza** [comment]
@GQAssurance I believe this solution addresses your bullet points.

**Comment by shawnCaza** [comment]
You're right the Milestone JSON API only goes back to 113. Polling both the old XML and JSON for drivers could assist with people needing to test old drivers.

**Comment by GQAssurance** [comment]
Yes I saw you handled the directory in the zip a slightly different way than I did.

The JSON apis do list Chrome versions 113 & 114, but they do not include download links.  So the new JSONs are only reliable for versions 115+

I am proposing an alternate PR to support 115, which is designed to be fully backwards compatible: 
 https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/pull/50

**Comment by GQAssurance** [comment]
It looks like 2 of us simultaneously came up with different solutions to support 115+

@shawnCaza [has a PR with efficient changes](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/pull/49) that will not support any chrome lower than 115
@GQAssurance [has a backwards compatible PR](https://github.com/yeongbin-jo/python-chromedriver-autoinstaller/pull/50) that keeps the old complexity

It might be worthwhile for @yeongbin-jo to express a preference

**Pull request closed without merging**
