### PR TITLE
Option to specify path to download the chromedriver.exe to

### PR DESCRIPTION
**Pull request by davidwickerhf**
Substituted the cwd argument in the `chromedriver_autoinstaller.install()` method to a `path `argument (str), which will specify the folder (directory) to install the chromedrivers to.

### CODE REVIEW

**Comment by epsilon-deltta** [comment]
this is what im finding . it looks more general

**Comment by StefanoGITA** [comment]
I also think this is a good idea

**Review by cauvery — APPROVED** [review]
Thanks for this, looks good. I was thinking to do this and found it.

**Review by SteveEmmanuel — APPROVED** [review]
Looks good.

**Pull request merged**
